### Supplementary Fig. 5: agreement of VFCs with reference families

In [1]:
import pandas as pd

df_v = pd.read_excel('../data/Supplementary_Data_1_vOTU_metadata.xlsx', usecols=['votu_id','VFC','host_phylum'])
df_vr = pd.read_excel('../data/Supplementary_Data_2_hierarchical_clustering_of_SPMP_and_reference_vOTUs.xlsx', usecols=['votu_id','VFC','dataset','Family','Subfamily'])
df_vc = pd.read_excel('../data/Supplementary_Data_3_VFC_metadata.xlsx', usecols=['VFC','VC_size'])

In [2]:
def show_counts_proportions(fam, groups=['VFC']):
    return pd.concat(
        [
            fam[groups].value_counts(),
            fam[groups].value_counts(normalize=True)
        ],
        axis=1,
        keys=['count', 'proportion']
    )

"All best hits of ICTV-ratified families (underlined) with non-singleton VFCs are shown."

*Inoviridae* and *Winoviridae* are not tabulated as their best-hits are not a non-singleton VFC.

In [3]:
nonsingletonVFCs = df_vc[df_vc.VC_size > 1].VFC.tolist()

df_vr[(df_vr.dataset == 'ICTV') & df_vr.VFC.isin(nonsingletonVFCs)][['Family','VFC']].value_counts(sort=False)

Family             VFC
Aliceevansviridae  109    113
                   218     11
Autographiviridae  125    187
                   326     35
Crevaviridae       117      4
Drexlerviridae     220    236
Inoviridae         175      7
Intestiviridae     49      18
Konodaiviridae     43       3
Microviridae       65       6
Peduoviridae       47     103
                   90      21
Steigviridae       242     16
Suoliviridae       67      35
Toyamaviridae      63       1
Umezonoviridae     243     55
Winoviridae        3        1
Name: count, dtype: int64

Heliusvirales

In [4]:
show_counts_proportions(df_vr[df_vr.dataset == 'Heliusvirales'])

     count  proportion
VFC
1      712    0.948069
534     19    0.025300
45       9    0.011984
673      4    0.005326
816      2    0.002663
817      2    0.002663
262      1    0.001332
992      1    0.001332
993      1    0.001332

Tsurumiviridae

In [5]:
show_counts_proportions(df_vr[df_vr.Family == 'Tsurumiviridae'])

     count  proportion
VFC
13      85    0.988372
35       1    0.011628

Okuboviridae

In [6]:
show_counts_proportions(df_vr[df_vr.Family == 'Okuboviridae'])

     count  proportion
VFC
16      70         1.0

Konodaiviridae

In [7]:
show_counts_proportions(df_vr[df_vr.Family == 'Konodaiviridae'])

     count  proportion
VFC
43      64         1.0

crAssphage-α

In [8]:
show_counts_proportions(df_vr.loc[(df_vr.Family == 'Intestiviridae') | ((df_vr.dataset == 'Yutin2021') & (df_vr.Subfamily == 'alpha'))])

     count  proportion
VFC
49     132         1.0

crAssphage-β

In [9]:
show_counts_proportions(df_vr.loc[(df_vr.Family == 'Steigviridae') | ((df_vr.dataset == 'Yutin2021') & (df_vr.Family == 'beta'))])

     count  proportion
VFC
242     71    0.986111
884      1    0.013889

crAssphage-γ

In [10]:
show_counts_proportions(df_vr.loc[(df_vr.Family == 'Crevaviridae') | ((df_vr.dataset == 'Yutin2021') & (df_vr.Subfamily == 'gamma'))])

     count  proportion
VFC
117     60         1.0

crAssphage-δ

In [11]:
show_counts_proportions(df_vr.loc[(df_vr.Family == 'Suoliviridae') | ((df_vr.dataset == 'Yutin2021') & (df_vr.Family == 'delta'))])

     count  proportion
VFC
67     217    0.995413
700      1    0.004587

crAssphage-ε

In [12]:
show_counts_proportions(df_vr.loc[(df_vr.dataset == 'Yutin2021') & (df_vr.Family == 'epsilon')])

     count  proportion
VFC
123     30         1.0

crAssphage-ζ

In [13]:
show_counts_proportions(df_vr.loc[(df_vr.dataset == 'Yutin2021') & (df_vr.Family == 'zeta')])

     count  proportion
VFC
142     69         1.0

Peduoviridae

"one of the *Peduoviridae* VFCs only infects Proteobacteria while the other infects Desulfobacterota hosts"

In [14]:
show_counts_proportions(df_vr.loc[df_vr.Family == 'Peduoviridae'])

     count  proportion
VFC
47     103    0.830645
90      21    0.169355

In [15]:
df_v.loc[df_v.VFC.isin([47,90])][['VFC','host_phylum']].value_counts()

VFC   host_phylum
47.0  Proteobacteria      28
90.0  Desulfobacterota     8
      Proteobacteria       1
Name: count, dtype: int64

Toyamaviridae

In [16]:
show_counts_proportions(df_vr.loc[df_vr.Family == 'Toyamaviridae'])

     count  proportion
VFC
63      75    0.974026
404      1    0.012987
769      1    0.012987

Microviridae

"The 2 *Microviridae* VFCs correspond to the 2 ICTV-ratified subfamilies, *Bullavirinae* and *Gokushovirinae*."

In [17]:
show_counts_proportions(df_vr.loc[df_vr.Family == 'Microviridae'], groups=['VFC','Subfamily'])

                    count  proportion
VFC Subfamily
546 Bullavirinae       14         0.7
65  Gokushovirinae      6         0.3

Shinjukuviridae

In [18]:
show_counts_proportions(df_vr.loc[df_vr.Family == 'Shinjukuviridae'])

     count  proportion
VFC
108     52         1.0

Aliceevansviridae

In [19]:
show_counts_proportions(df_vr.loc[df_vr.Family == 'Aliceevansviridae'])

     count  proportion
VFC
109    113     0.91129
218     11     0.08871

Autographiviridae

In [20]:
show_counts_proportions(df_vr.loc[df_vr.Family == 'Autographiviridae'])

     count  proportion
VFC
125    214    0.539043
458     94    0.236776
494     48    0.120907
326     38    0.095718
692      3    0.007557

Flandersviridae

In [21]:
show_counts_proportions(df_vr.loc[df_vr.Family == 'Flandersviridae'])

     count  proportion
VFC
183    298         1.0

Drexlerviridae

In [22]:
show_counts_proportions(df_vr.loc[df_vr.Family == 'Drexlerviridae'])

     count  proportion
VFC
220    254         1.0

Umezonoviridae

In [23]:
show_counts_proportions(df_vr.loc[df_vr.Family == 'Umezonoviridae'])

     count  proportion
VFC
243    112         1.0